data_collection:
  jam_cam_website: "http://jamcams.tfl.gov.uk/00001."
  tims_camera_list:
    [
      "00001.03601",
      "00001.07591",
      "00001.01252",
      "00001.06597",
      "00001.08853",
      "00001.06510",
      "00001.04280",
      "00001.04534",
      "00001.06590",
      "00001.07382",
      "00001.04328",
      "00001.06514",
      "00001.03604",
      "00001.06501",
      "00001.05900",
      "00001.03490",
      "00001.08926",
      "00001.07355",
      "00001.04336",
      "00001.09560",
    ]
  tims_file_website: "https://s3-eu-west-1.amazonaws.com/roads.data.tfl.gov.uk"
  tims_download_website: "http://roads.data.tfl.gov.uk/TIMS/"
  tfl_camera_api: "https://api.tfl.gov.uk/Place/Type/jamcam"
  jamcam_url: "https://s3-eu-west-1.amazonaws.com/jamcams.tfl.gov.uk/"
  iterations: 0
  delay: 3

data_renaming:
  old_path: "raw/video_data_new"
  new_path: "raw/videos"
  date_format: "%Y%m%d-%H%M%S"

modelling:
  # obj detection
  detection_model: "yolov3_tf"
  detection_implementation: "cvlib"
  detection_iou_threshold: 0.05
  detection_confidence_threshold: 0.2
  detection_nms_threshold: 0.2

  # tracking
  selected_labels: ["car", "truck", "bus", "motorbike"]
  opencv_tracker_type: "CSRT"
  iou_threshold: 0.05 #controls how much two objects' bboxes must overlap to be considered the "same"
  detection_frequency: 25

  #stop starts
  iou_convolution_window: 15
  smoothing_method: "moving_avg"
  stop_start_iou_threshold: 0.80

reporting:
  chunk_size: 5
  dtype:
    camera_id: 'category'
  video_level_column_order: ["camera_id", "video_upload_datetime", "vehicle_type", "counts", "starts", "stops", "parked"]
  video_level_stats: ['counts', 'stops','starts','parked']
