# Parameters to be used in the pipeline

example_test_data_ratio: 0.2
example_num_train_iter: 10000
example_learning_rate: 0.01

[DATA_COLLECTION]
jam_cam_website: "http://jamcams.tfl.gov.uk/00001."
camera_list: ["06641", "06640", "06595", "06508", "06597", "06607", "06608", "06598", # imperial area
              '07452', '08860', '08859', '08858', '08863', '08753', '07301'] # oxford street area
tims_website: 'https://s3-eu-west-1.amazonaws.com/roads.data.tfl.gov.uk'

