data_collection:
  jam_cam_website: "http://jamcams.tfl.gov.uk/00001."
  tims_camera_list:
    [
      "00001.03601",
      "00001.07591",
      "00001.01252",
      "00001.06597",
      "00001.08853",
      "00001.06510",
      "00001.04280",
      "00001.04534",
      "00001.06590",
      "00001.07382",
      "00001.04328",
      "00001.06514",
      "00001.03604",
      "00001.06501",
      "00001.05900",
      "00001.03490",
      "00001.08926",
      "00001.07355",
      "00001.04336",
      "00001.09560"
    ]
  tims_file_website: "https://s3-eu-west-1.amazonaws.com/roads.data.tfl.gov.uk"
  tims_download_website: "http://roads.data.tfl.gov.uk/TIMS/"
  tfl_camera_api: "https://api.tfl.gov.uk/Place/Type/jamcam"
  jamcam_url: "https://s3-eu-west-1.amazonaws.com/jamcams.tfl.gov.uk/"
  iterations: 0
  delay: 3

data_renaming:
  old_path: "raw/video_data_new"
  new_path: "raw/videos"
  date_format: "%Y%m%d-%H%M%S"

pipeline_settings:
  dataset_ref_name: "tims_cameras_all"
  chunk_size: 10

eval_pipeline_settings:
  eval_ref_name: "annotated_videos"
  eval_chunk_size: 7
  eval_params_order: ['tracker_type', 'detection_model', "detection_frequency", "detection_iou_threshold", "stop_start_iou_threshold"]
  eval_tracker_types: ['kcf', 'mosse', 'csrt', 'medianflow', 'tld', 'boosting']
  eval_detection_models: ['yolov3-tiny', 'yolov3_tf']
  eval_detection_frequency: [4, 6]
  eval_detection_iou_threshold: [0.1, 0.05, 0.10 , 0.4, 0.45, 0.50]
  eval_stop_start_iou_threshold: [0.75, 0.80, 0.85, 0.90]

modelling:
  # obj detection
  default_detection_model: "yolov3_tf"
  detection_implementation: "cvlib"
  detection_iou_threshold: 0.05
  detection_confidence_threshold: 0.2
  detection_nms_threshold: 0.2
  GPU_number: 2

  # tracking
  selected_labels: ["car", "truck", "bus", "motorbike"]
  default_tracker_type: "csrt"
  iou_threshold: 0.05 #controls how much two objects' bboxes must overlap to be considered the "same"
  detection_frequency: 4
  skip_no_of_frames: 3

  #stop starts
  iou_convolution_window: 15
  smoothing_method: "moving_avg"
  stop_start_iou_threshold: 0.80

reporting:
  dtype:
    camera_id: 'category'
  video_level_column_order: ["camera_id", "video_upload_datetime", "vehicle_type", "counts", "starts", "stops", "parked"]
  video_level_stats: ['counts', 'stops','starts','parked']
