data_collection:
  jam_cam_website: "http://jamcams.tfl.gov.uk/00001."
  tfl_camera_api: "https://api.tfl.gov.uk/Place/Type/jamcam"
  jamcam_url: "https://s3-eu-west-1.amazonaws.com/jamcams.tfl.gov.uk/"
  iterations: 0
  delay: 3

static_pipeline:
  load_ref_file: False
  ref_file_name: "example_dataset"
  camera_list:
    [   
      "00001.03601",
      "00001.07591",
      "00001.01252",
      "00001.06597",
      "00001.08853",
      "00001.06510",
      "00001.04280",
      "00001.04534",
      "00001.06590",
      "00001.07382",
      "00001.04328",
      "00001.06514",
      "00001.03604",
      "00001.06501",
      "00001.05900",
      "00001.03490",
      "00001.08926",
      "00001.07355",
      "00001.04336",
      "00001.09560"
    ]
  from_date: "2019-07-17" 
  to_date: "2019-07-17"
  from_time: "00-00-00"
  to_time: "23-59-59"

data_renaming: # TODO: remove later when renaming finished
  old_path: "raw/video_data_new"
  new_path: "raw/videos"
  date_format: "%Y%m%d-%H%M%S"

modelling:
  # obj detection
  detection_model: "traffic_tf"  # yolov3_opencv, yolov3-tiny_opencv, yolov3_tf, traffic_tf, YOURCUSTOMMODEL_tf...
  detection_iou_threshold: 0.5
  detection_confidence_threshold: 0.2

  # tracking
  selected_labels: ["car", "truck", "bus", "motorbike"]
  opencv_tracker_type: "mosse"
  iou_threshold: 0.05 #controls how much two objects' bboxes must overlap to be considered the "same"
  detection_frequency: 4
  skip_no_of_frames: 3

  #stop starts
  iou_convolution_window: 15
  smoothing_method: "moving_avg"
  stop_start_iou_threshold: 0.75

  # others
  delete_processed_videos: False

reporting:
  chunk_size: 10
  dtype:
    camera_id: 'category'
  video_level_column_order: ["camera_id", "video_upload_datetime", "vehicle_type", "counts", "starts", "stops", "parked"]
  video_level_stats: ['counts', 'stops','starts','parked']
